# Generated by Django 5.1.6 on 2025-03-08 15:43

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="imagem",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                upload_to="get_file_path",
                variations={"thumb": {"crop": True, "height": 480, "width": 480}},
                verbose_name="Imagem",
            ),
        ),
    ]
